apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-secret
        property: POSTGRES_USER
    - secretKey: password
      remoteRef:
        key: postgres-secret
        property: POSTGRES_PASSWORD
